// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: confidence/flags/admin/v1/events/events.proto

package events

import (
	_ "github.com/spotify/confidence-resolver-rust/openfeature-provider/go/confidence/proto/confidence/events/v1"
	v1 "github.com/spotify/confidence-resolver-rust/openfeature-provider/go/confidence/proto/confidence/flags/admin/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Occurs when a new flag is created
type FlagCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The flag that was created
	Flag          *v1.Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagCreated) Reset() {
	*x = FlagCreated{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagCreated) ProtoMessage() {}

func (x *FlagCreated) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagCreated.ProtoReflect.Descriptor instead.
func (*FlagCreated) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *FlagCreated) GetFlag() *v1.Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// Occurs when a flag has been updated
type FlagUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The flag that was updated
	Flag          *v1.Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagUpdated) Reset() {
	*x = FlagUpdated{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagUpdated) ProtoMessage() {}

func (x *FlagUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagUpdated.ProtoReflect.Descriptor instead.
func (*FlagUpdated) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{1}
}

func (x *FlagUpdated) GetFlag() *v1.Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// Occurs when a flag is archived
type FlagArchived struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The flag that was archived
	Flag          *v1.Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagArchived) Reset() {
	*x = FlagArchived{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagArchived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagArchived) ProtoMessage() {}

func (x *FlagArchived) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagArchived.ProtoReflect.Descriptor instead.
func (*FlagArchived) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{2}
}

func (x *FlagArchived) GetFlag() *v1.Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// Occurs when a segment is created
type SegmentCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The segment that was created
	Segment       *v1.Segment `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentCreated) Reset() {
	*x = SegmentCreated{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentCreated) ProtoMessage() {}

func (x *SegmentCreated) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentCreated.ProtoReflect.Descriptor instead.
func (*SegmentCreated) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentCreated) GetSegment() *v1.Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

// Occurs when a segment is updated
type SegmentUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The segment that was updated
	Segment       *v1.Segment `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentUpdated) Reset() {
	*x = SegmentUpdated{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentUpdated) ProtoMessage() {}

func (x *SegmentUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentUpdated.ProtoReflect.Descriptor instead.
func (*SegmentUpdated) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentUpdated) GetSegment() *v1.Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

// Occurs when a segment is allocated
type SegmentAllocated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The segment that was allocated
	Segment       *v1.Segment `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentAllocated) Reset() {
	*x = SegmentAllocated{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentAllocated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentAllocated) ProtoMessage() {}

func (x *SegmentAllocated) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentAllocated.ProtoReflect.Descriptor instead.
func (*SegmentAllocated) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{5}
}

func (x *SegmentAllocated) GetSegment() *v1.Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

// Occurs when a segment is archived
type SegmentArchived struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The segment that was archived
	Segment       *v1.Segment `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentArchived) Reset() {
	*x = SegmentArchived{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentArchived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentArchived) ProtoMessage() {}

func (x *SegmentArchived) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentArchived.ProtoReflect.Descriptor instead.
func (*SegmentArchived) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{6}
}

func (x *SegmentArchived) GetSegment() *v1.Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

// Occurs when a Rule is enabled
type RuleEnabled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Rule that was enabled
	Rule          *v1.Flag_Rule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleEnabled) Reset() {
	*x = RuleEnabled{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleEnabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleEnabled) ProtoMessage() {}

func (x *RuleEnabled) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleEnabled.ProtoReflect.Descriptor instead.
func (*RuleEnabled) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{7}
}

func (x *RuleEnabled) GetRule() *v1.Flag_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// Occurs when a Rule is disabled
type RuleDisabled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Rule that was disabled
	Rule          *v1.Flag_Rule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleDisabled) Reset() {
	*x = RuleDisabled{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleDisabled) ProtoMessage() {}

func (x *RuleDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleDisabled.ProtoReflect.Descriptor instead.
func (*RuleDisabled) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{8}
}

func (x *RuleDisabled) GetRule() *v1.Flag_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// A materialized segment was created.
type MaterializedSegmentCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created materialized segment.
	MaterializedSegment *v1.MaterializedSegment `protobuf:"bytes,1,opt,name=materialized_segment,json=materializedSegment,proto3" json:"materialized_segment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MaterializedSegmentCreated) Reset() {
	*x = MaterializedSegmentCreated{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedSegmentCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedSegmentCreated) ProtoMessage() {}

func (x *MaterializedSegmentCreated) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedSegmentCreated.ProtoReflect.Descriptor instead.
func (*MaterializedSegmentCreated) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{9}
}

func (x *MaterializedSegmentCreated) GetMaterializedSegment() *v1.MaterializedSegment {
	if x != nil {
		return x.MaterializedSegment
	}
	return nil
}

// A materialized segment was updated.
type MaterializedSegmentUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated materialized segment.
	MaterializedSegment *v1.MaterializedSegment `protobuf:"bytes,1,opt,name=materialized_segment,json=materializedSegment,proto3" json:"materialized_segment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MaterializedSegmentUpdated) Reset() {
	*x = MaterializedSegmentUpdated{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedSegmentUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedSegmentUpdated) ProtoMessage() {}

func (x *MaterializedSegmentUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedSegmentUpdated.ProtoReflect.Descriptor instead.
func (*MaterializedSegmentUpdated) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{10}
}

func (x *MaterializedSegmentUpdated) GetMaterializedSegment() *v1.MaterializedSegment {
	if x != nil {
		return x.MaterializedSegment
	}
	return nil
}

// A materialized segment was deleted.
type MaterializedSegmentDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The deleted materialized segment.
	MaterializedSegment string `protobuf:"bytes,1,opt,name=materialized_segment,json=materializedSegment,proto3" json:"materialized_segment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MaterializedSegmentDeleted) Reset() {
	*x = MaterializedSegmentDeleted{}
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedSegmentDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedSegmentDeleted) ProtoMessage() {}

func (x *MaterializedSegmentDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_events_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedSegmentDeleted.ProtoReflect.Descriptor instead.
func (*MaterializedSegmentDeleted) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP(), []int{11}
}

func (x *MaterializedSegmentDeleted) GetMaterializedSegment() string {
	if x != nil {
		return x.MaterializedSegment
	}
	return ""
}

var File_confidence_flags_admin_v1_events_events_proto protoreflect.FileDescriptor

const file_confidence_flags_admin_v1_events_events_proto_rawDesc = "" +
	"\n" +
	"-confidence/flags/admin/v1/events/events.proto\x12 confidence.flags.admin.v1.events\x1a&confidence/events/v1/annotations.proto\x1a%confidence/flags/admin/v1/types.proto\"n\n" +
	"\vFlagCreated\x123\n" +
	"\x04flag\x18\x01 \x01(\v2\x1f.confidence.flags.admin.v1.FlagR\x04flag:*\xf2\xb7\xbf\x10%\b\x01\x12!Occurs when a new flag is created\"p\n" +
	"\vFlagUpdated\x123\n" +
	"\x04flag\x18\x01 \x01(\v2\x1f.confidence.flags.admin.v1.FlagR\x04flag:,\xf2\xb7\xbf\x10'\b\x01\x12#Occurs when a flag has been updated\"l\n" +
	"\fFlagArchived\x123\n" +
	"\x04flag\x18\x01 \x01(\v2\x1f.confidence.flags.admin.v1.FlagR\x04flag:'\xf2\xb7\xbf\x10\"\b\x01\x12\x1eOccurs when a flag is archived\"y\n" +
	"\x0eSegmentCreated\x12<\n" +
	"\asegment\x18\x01 \x01(\v2\".confidence.flags.admin.v1.SegmentR\asegment:)\xf2\xb7\xbf\x10$\b\x01\x12 Occurs when a segment is created\"y\n" +
	"\x0eSegmentUpdated\x12<\n" +
	"\asegment\x18\x01 \x01(\v2\".confidence.flags.admin.v1.SegmentR\asegment:)\xf2\xb7\xbf\x10$\b\x01\x12 Occurs when a segment is updated\"}\n" +
	"\x10SegmentAllocated\x12<\n" +
	"\asegment\x18\x01 \x01(\v2\".confidence.flags.admin.v1.SegmentR\asegment:+\xf2\xb7\xbf\x10&\b\x01\x12\"Occurs when a segment is allocated\"{\n" +
	"\x0fSegmentArchived\x12<\n" +
	"\asegment\x18\x01 \x01(\v2\".confidence.flags.admin.v1.SegmentR\asegment:*\xf2\xb7\xbf\x10%\b\x01\x12!Occurs when a segment is archived\"o\n" +
	"\vRuleEnabled\x128\n" +
	"\x04rule\x18\x01 \x01(\v2$.confidence.flags.admin.v1.Flag.RuleR\x04rule:&\xf2\xb7\xbf\x10!\b\x01\x12\x1dOccurs when a Rule is enabled\"q\n" +
	"\fRuleDisabled\x128\n" +
	"\x04rule\x18\x01 \x01(\v2$.confidence.flags.admin.v1.Flag.RuleR\x04rule:'\xf2\xb7\xbf\x10\"\b\x01\x12\x1eOccurs when a Rule is disabled\"\xb7\x01\n" +
	"\x1aMaterializedSegmentCreated\x12a\n" +
	"\x14materialized_segment\x18\x01 \x01(\v2..confidence.flags.admin.v1.MaterializedSegmentR\x13materializedSegment:6\xf2\xb7\xbf\x101\b\x01\x12-Occurs when a materialized segment is created\"\xb7\x01\n" +
	"\x1aMaterializedSegmentUpdated\x12a\n" +
	"\x14materialized_segment\x18\x01 \x01(\v2..confidence.flags.admin.v1.MaterializedSegmentR\x13materializedSegment:6\xf2\xb7\xbf\x101\b\x01\x12-Occurs when a materialized segment is updated\"\x87\x01\n" +
	"\x1aMaterializedSegmentDeleted\x121\n" +
	"\x14materialized_segment\x18\x01 \x01(\tR\x13materializedSegment:6\xf2\xb7\xbf\x101\b\x01\x12-Occurs when a materialized segment is deletedB=\n" +
	",com.spotify.confidence.flags.admin.v1.eventsB\vEventsProtoP\x01b\x06proto3"

var (
	file_confidence_flags_admin_v1_events_events_proto_rawDescOnce sync.Once
	file_confidence_flags_admin_v1_events_events_proto_rawDescData []byte
)

func file_confidence_flags_admin_v1_events_events_proto_rawDescGZIP() []byte {
	file_confidence_flags_admin_v1_events_events_proto_rawDescOnce.Do(func() {
		file_confidence_flags_admin_v1_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_flags_admin_v1_events_events_proto_rawDesc), len(file_confidence_flags_admin_v1_events_events_proto_rawDesc)))
	})
	return file_confidence_flags_admin_v1_events_events_proto_rawDescData
}

var file_confidence_flags_admin_v1_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_confidence_flags_admin_v1_events_events_proto_goTypes = []any{
	(*FlagCreated)(nil),                // 0: confidence.flags.admin.v1.events.FlagCreated
	(*FlagUpdated)(nil),                // 1: confidence.flags.admin.v1.events.FlagUpdated
	(*FlagArchived)(nil),               // 2: confidence.flags.admin.v1.events.FlagArchived
	(*SegmentCreated)(nil),             // 3: confidence.flags.admin.v1.events.SegmentCreated
	(*SegmentUpdated)(nil),             // 4: confidence.flags.admin.v1.events.SegmentUpdated
	(*SegmentAllocated)(nil),           // 5: confidence.flags.admin.v1.events.SegmentAllocated
	(*SegmentArchived)(nil),            // 6: confidence.flags.admin.v1.events.SegmentArchived
	(*RuleEnabled)(nil),                // 7: confidence.flags.admin.v1.events.RuleEnabled
	(*RuleDisabled)(nil),               // 8: confidence.flags.admin.v1.events.RuleDisabled
	(*MaterializedSegmentCreated)(nil), // 9: confidence.flags.admin.v1.events.MaterializedSegmentCreated
	(*MaterializedSegmentUpdated)(nil), // 10: confidence.flags.admin.v1.events.MaterializedSegmentUpdated
	(*MaterializedSegmentDeleted)(nil), // 11: confidence.flags.admin.v1.events.MaterializedSegmentDeleted
	(*v1.Flag)(nil),                    // 12: confidence.flags.admin.v1.Flag
	(*v1.Segment)(nil),                 // 13: confidence.flags.admin.v1.Segment
	(*v1.Flag_Rule)(nil),               // 14: confidence.flags.admin.v1.Flag.Rule
	(*v1.MaterializedSegment)(nil),     // 15: confidence.flags.admin.v1.MaterializedSegment
}
var file_confidence_flags_admin_v1_events_events_proto_depIdxs = []int32{
	12, // 0: confidence.flags.admin.v1.events.FlagCreated.flag:type_name -> confidence.flags.admin.v1.Flag
	12, // 1: confidence.flags.admin.v1.events.FlagUpdated.flag:type_name -> confidence.flags.admin.v1.Flag
	12, // 2: confidence.flags.admin.v1.events.FlagArchived.flag:type_name -> confidence.flags.admin.v1.Flag
	13, // 3: confidence.flags.admin.v1.events.SegmentCreated.segment:type_name -> confidence.flags.admin.v1.Segment
	13, // 4: confidence.flags.admin.v1.events.SegmentUpdated.segment:type_name -> confidence.flags.admin.v1.Segment
	13, // 5: confidence.flags.admin.v1.events.SegmentAllocated.segment:type_name -> confidence.flags.admin.v1.Segment
	13, // 6: confidence.flags.admin.v1.events.SegmentArchived.segment:type_name -> confidence.flags.admin.v1.Segment
	14, // 7: confidence.flags.admin.v1.events.RuleEnabled.rule:type_name -> confidence.flags.admin.v1.Flag.Rule
	14, // 8: confidence.flags.admin.v1.events.RuleDisabled.rule:type_name -> confidence.flags.admin.v1.Flag.Rule
	15, // 9: confidence.flags.admin.v1.events.MaterializedSegmentCreated.materialized_segment:type_name -> confidence.flags.admin.v1.MaterializedSegment
	15, // 10: confidence.flags.admin.v1.events.MaterializedSegmentUpdated.materialized_segment:type_name -> confidence.flags.admin.v1.MaterializedSegment
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_confidence_flags_admin_v1_events_events_proto_init() }
func file_confidence_flags_admin_v1_events_events_proto_init() {
	if File_confidence_flags_admin_v1_events_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_flags_admin_v1_events_events_proto_rawDesc), len(file_confidence_flags_admin_v1_events_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_confidence_flags_admin_v1_events_events_proto_goTypes,
		DependencyIndexes: file_confidence_flags_admin_v1_events_events_proto_depIdxs,
		MessageInfos:      file_confidence_flags_admin_v1_events_events_proto_msgTypes,
	}.Build()
	File_confidence_flags_admin_v1_events_events_proto = out.File
	file_confidence_flags_admin_v1_events_events_proto_goTypes = nil
	file_confidence_flags_admin_v1_events_events_proto_depIdxs = nil
}
