// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: confidence/events/v1/annotations.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persist       bool                   `protobuf:"varint,1,opt,name=persist,proto3" json:"persist,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSpec) Reset() {
	*x = EventSpec{}
	mi := &file_confidence_events_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSpec) ProtoMessage() {}

func (x *EventSpec) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_events_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSpec.ProtoReflect.Descriptor instead.
func (*EventSpec) Descriptor() ([]byte, []int) {
	return file_confidence_events_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *EventSpec) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *EventSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var file_confidence_events_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventSpec)(nil),
		Field:         4324222,
		Name:          "confidence.events.v1.event",
		Tag:           "bytes,4324222,opt,name=event",
		Filename:      "confidence/events/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional confidence.events.v1.EventSpec event = 4324222;
	E_Event = &file_confidence_events_v1_annotations_proto_extTypes[0]
)

var File_confidence_events_v1_annotations_proto protoreflect.FileDescriptor

const file_confidence_events_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"&confidence/events/v1/annotations.proto\x12\x14confidence.events.v1\x1a google/protobuf/descriptor.proto\"G\n" +
	"\tEventSpec\x12\x18\n" +
	"\apersist\x18\x01 \x01(\bR\apersist\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription:Y\n" +
	"\x05event\x12\x1f.google.protobuf.MessageOptions\x18\xfe\xf6\x87\x02 \x01(\v2\x1f.confidence.events.v1.EventSpecR\x05eventB7\n" +
	"!com.spotify.confidence.commons.v1B\x10AnnotationsProtoP\x01b\x06proto3"

var (
	file_confidence_events_v1_annotations_proto_rawDescOnce sync.Once
	file_confidence_events_v1_annotations_proto_rawDescData []byte
)

func file_confidence_events_v1_annotations_proto_rawDescGZIP() []byte {
	file_confidence_events_v1_annotations_proto_rawDescOnce.Do(func() {
		file_confidence_events_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_events_v1_annotations_proto_rawDesc), len(file_confidence_events_v1_annotations_proto_rawDesc)))
	})
	return file_confidence_events_v1_annotations_proto_rawDescData
}

var file_confidence_events_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_confidence_events_v1_annotations_proto_goTypes = []any{
	(*EventSpec)(nil),                   // 0: confidence.events.v1.EventSpec
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_confidence_events_v1_annotations_proto_depIdxs = []int32{
	1, // 0: confidence.events.v1.event:extendee -> google.protobuf.MessageOptions
	0, // 1: confidence.events.v1.event:type_name -> confidence.events.v1.EventSpec
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_confidence_events_v1_annotations_proto_init() }
func file_confidence_events_v1_annotations_proto_init() {
	if File_confidence_events_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_events_v1_annotations_proto_rawDesc), len(file_confidence_events_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_confidence_events_v1_annotations_proto_goTypes,
		DependencyIndexes: file_confidence_events_v1_annotations_proto_depIdxs,
		MessageInfos:      file_confidence_events_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_confidence_events_v1_annotations_proto_extTypes,
	}.Build()
	File_confidence_events_v1_annotations_proto = out.File
	file_confidence_events_v1_annotations_proto_goTypes = nil
	file_confidence_events_v1_annotations_proto_depIdxs = nil
}
