// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: confidence/api/annotations.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_confidence_api_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_api_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_confidence_api_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Rate limit specification that is applied on global rates per account
type RateLimitSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpsLimit      int32                  `protobuf:"varint,1,opt,name=rps_limit,json=rpsLimit,proto3" json:"rps_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitSpec) Reset() {
	*x = RateLimitSpec{}
	mi := &file_confidence_api_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitSpec) ProtoMessage() {}

func (x *RateLimitSpec) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_api_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitSpec.ProtoReflect.Descriptor instead.
func (*RateLimitSpec) Descriptor() ([]byte, []int) {
	return file_confidence_api_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitSpec) GetRpsLimit() int32 {
	if x != nil {
		return x.RpsLimit
	}
	return 0
}

type ValidationSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regex         string                 `protobuf:"bytes,1,opt,name=regex,proto3" json:"regex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationSpec) Reset() {
	*x = ValidationSpec{}
	mi := &file_confidence_api_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationSpec) ProtoMessage() {}

func (x *ValidationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_api_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationSpec.ProtoReflect.Descriptor instead.
func (*ValidationSpec) Descriptor() ([]byte, []int) {
	return file_confidence_api_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationSpec) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

var file_confidence_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Resource)(nil),
		Field:         4399226,
		Name:          "confidence.api.resource_method",
		Tag:           "bytes,4399226,opt,name=resource_method",
		Filename:      "confidence/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RateLimitSpec)(nil),
		Field:         4399227,
		Name:          "confidence.api.rate_limit",
		Tag:           "bytes,4399227,opt,name=rate_limit",
		Filename:      "confidence/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         4399229,
		Name:          "confidence.api.service_name",
		Tag:           "bytes,4399229,opt,name=service_name",
		Filename:      "confidence/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         4399228,
		Name:          "confidence.api.hosts",
		Tag:           "bytes,4399228,rep,name=hosts",
		Filename:      "confidence/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*RateLimitSpec)(nil),
		Field:         4399230,
		Name:          "confidence.api.service_rate_limit",
		Tag:           "bytes,4399230,opt,name=service_rate_limit",
		Filename:      "confidence/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ValidationSpec)(nil),
		Field:         4324223,
		Name:          "confidence.api.validation",
		Tag:           "bytes,4324223,opt,name=validation",
		Filename:      "confidence/api/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional confidence.api.Resource resource_method = 4399226;
	E_ResourceMethod = &file_confidence_api_annotations_proto_extTypes[0]
	// optional confidence.api.RateLimitSpec rate_limit = 4399227;
	E_RateLimit = &file_confidence_api_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string service_name = 4399229;
	E_ServiceName = &file_confidence_api_annotations_proto_extTypes[2]
	// repeated string hosts = 4399228;
	E_Hosts = &file_confidence_api_annotations_proto_extTypes[3]
	// optional confidence.api.RateLimitSpec service_rate_limit = 4399230;
	E_ServiceRateLimit = &file_confidence_api_annotations_proto_extTypes[4]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional confidence.api.ValidationSpec validation = 4324223;
	E_Validation = &file_confidence_api_annotations_proto_extTypes[5]
)

var File_confidence_api_annotations_proto protoreflect.FileDescriptor

const file_confidence_api_annotations_proto_rawDesc = "" +
	"\n" +
	" confidence/api/annotations.proto\x12\x0econfidence.api\x1a google/protobuf/descriptor.proto\"\x1e\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\",\n" +
	"\rRateLimitSpec\x12\x1b\n" +
	"\trps_limit\x18\x01 \x01(\x05R\brpsLimit\"&\n" +
	"\x0eValidationSpec\x12\x14\n" +
	"\x05regex\x18\x01 \x01(\tR\x05regex:d\n" +
	"\x0fresource_method\x12\x1e.google.protobuf.MethodOptions\x18\xfa\xc0\x8c\x02 \x01(\v2\x18.confidence.api.ResourceR\x0eresourceMethod:_\n" +
	"\n" +
	"rate_limit\x12\x1e.google.protobuf.MethodOptions\x18\xfb\xc0\x8c\x02 \x01(\v2\x1d.confidence.api.RateLimitSpecR\trateLimit:E\n" +
	"\fservice_name\x12\x1f.google.protobuf.ServiceOptions\x18\xfd\xc0\x8c\x02 \x01(\tR\vserviceName:8\n" +
	"\x05hosts\x12\x1f.google.protobuf.ServiceOptions\x18\xfc\xc0\x8c\x02 \x03(\tR\x05hosts:o\n" +
	"\x12service_rate_limit\x12\x1f.google.protobuf.ServiceOptions\x18\xfe\xc0\x8c\x02 \x01(\v2\x1d.confidence.api.RateLimitSpecR\x10serviceRateLimit:`\n" +
	"\n" +
	"validation\x12\x1d.google.protobuf.FieldOptions\x18\xff\xf6\x87\x02 \x01(\v2\x1e.confidence.api.ValidationSpecR\n" +
	"validationB3\n" +
	"\x1acom.spotify.confidence.apiB\x13ApiAnnotationsProtoP\x01b\x06proto3"

var (
	file_confidence_api_annotations_proto_rawDescOnce sync.Once
	file_confidence_api_annotations_proto_rawDescData []byte
)

func file_confidence_api_annotations_proto_rawDescGZIP() []byte {
	file_confidence_api_annotations_proto_rawDescOnce.Do(func() {
		file_confidence_api_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_api_annotations_proto_rawDesc), len(file_confidence_api_annotations_proto_rawDesc)))
	})
	return file_confidence_api_annotations_proto_rawDescData
}

var file_confidence_api_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_confidence_api_annotations_proto_goTypes = []any{
	(*Resource)(nil),                    // 0: confidence.api.Resource
	(*RateLimitSpec)(nil),               // 1: confidence.api.RateLimitSpec
	(*ValidationSpec)(nil),              // 2: confidence.api.ValidationSpec
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
	(*descriptorpb.FieldOptions)(nil),   // 5: google.protobuf.FieldOptions
}
var file_confidence_api_annotations_proto_depIdxs = []int32{
	3,  // 0: confidence.api.resource_method:extendee -> google.protobuf.MethodOptions
	3,  // 1: confidence.api.rate_limit:extendee -> google.protobuf.MethodOptions
	4,  // 2: confidence.api.service_name:extendee -> google.protobuf.ServiceOptions
	4,  // 3: confidence.api.hosts:extendee -> google.protobuf.ServiceOptions
	4,  // 4: confidence.api.service_rate_limit:extendee -> google.protobuf.ServiceOptions
	5,  // 5: confidence.api.validation:extendee -> google.protobuf.FieldOptions
	0,  // 6: confidence.api.resource_method:type_name -> confidence.api.Resource
	1,  // 7: confidence.api.rate_limit:type_name -> confidence.api.RateLimitSpec
	1,  // 8: confidence.api.service_rate_limit:type_name -> confidence.api.RateLimitSpec
	2,  // 9: confidence.api.validation:type_name -> confidence.api.ValidationSpec
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	6,  // [6:10] is the sub-list for extension type_name
	0,  // [0:6] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_confidence_api_annotations_proto_init() }
func file_confidence_api_annotations_proto_init() {
	if File_confidence_api_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_api_annotations_proto_rawDesc), len(file_confidence_api_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_confidence_api_annotations_proto_goTypes,
		DependencyIndexes: file_confidence_api_annotations_proto_depIdxs,
		MessageInfos:      file_confidence_api_annotations_proto_msgTypes,
		ExtensionInfos:    file_confidence_api_annotations_proto_extTypes,
	}.Build()
	File_confidence_api_annotations_proto = out.File
	file_confidence_api_annotations_proto_goTypes = nil
	file_confidence_api_annotations_proto_depIdxs = nil
}
