// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: mock/flags_resolver.proto

package mockpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The service that allows to report flag assigned and other client-side flag
// operations, useful when the resolve engine runs on the customer's premises
// (e.g. side-car)
type WriteFlagLogsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FlagAssigned      [][]byte               `protobuf:"bytes,1,rep,name=flag_assigned,json=flagAssigned,proto3" json:"flag_assigned,omitempty"`
	ClientResolveInfo [][]byte               `protobuf:"bytes,3,rep,name=client_resolve_info,json=clientResolveInfo,proto3" json:"client_resolve_info,omitempty"`
	FlagResolveInfo   [][]byte               `protobuf:"bytes,4,rep,name=flag_resolve_info,json=flagResolveInfo,proto3" json:"flag_resolve_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WriteFlagLogsRequest) Reset() {
	*x = WriteFlagLogsRequest{}
	mi := &file_mock_flags_resolver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFlagLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFlagLogsRequest) ProtoMessage() {}

func (x *WriteFlagLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mock_flags_resolver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFlagLogsRequest.ProtoReflect.Descriptor instead.
func (*WriteFlagLogsRequest) Descriptor() ([]byte, []int) {
	return file_mock_flags_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *WriteFlagLogsRequest) GetFlagAssigned() [][]byte {
	if x != nil {
		return x.FlagAssigned
	}
	return nil
}

func (x *WriteFlagLogsRequest) GetClientResolveInfo() [][]byte {
	if x != nil {
		return x.ClientResolveInfo
	}
	return nil
}

func (x *WriteFlagLogsRequest) GetFlagResolveInfo() [][]byte {
	if x != nil {
		return x.FlagResolveInfo
	}
	return nil
}

type WriteFlagLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFlagLogsResponse) Reset() {
	*x = WriteFlagLogsResponse{}
	mi := &file_mock_flags_resolver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFlagLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFlagLogsResponse) ProtoMessage() {}

func (x *WriteFlagLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mock_flags_resolver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFlagLogsResponse.ProtoReflect.Descriptor instead.
func (*WriteFlagLogsResponse) Descriptor() ([]byte, []int) {
	return file_mock_flags_resolver_proto_rawDescGZIP(), []int{1}
}

var File_mock_flags_resolver_proto protoreflect.FileDescriptor

const file_mock_flags_resolver_proto_rawDesc = "" +
	"\n" +
	"\x19mock/flags_resolver.proto\x12\x1cconfidence.flags.resolver.v1\x1a\x1cgoogle/api/annotations.proto\"\x97\x01\n" +
	"\x14WriteFlagLogsRequest\x12#\n" +
	"\rflag_assigned\x18\x01 \x03(\fR\fflagAssigned\x12.\n" +
	"\x13client_resolve_info\x18\x03 \x03(\fR\x11clientResolveInfo\x12*\n" +
	"\x11flag_resolve_info\x18\x04 \x03(\fR\x0fflagResolveInfo\"\x17\n" +
	"\x15WriteFlagLogsResponse2\xb5\x01\n" +
	"\x19InternalFlagLoggerService\x12\x97\x01\n" +
	"\rWriteFlagLogs\x122.confidence.flags.resolver.v1.WriteFlagLogsRequest\x1a3.confidence.flags.resolver.v1.WriteFlagLogsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/flagLogs:writeBVZTgithub.com/spotify/confidence-resolver-rust/mock-support-server/genproto/mock;mockpbb\x06proto3"

var (
	file_mock_flags_resolver_proto_rawDescOnce sync.Once
	file_mock_flags_resolver_proto_rawDescData []byte
)

func file_mock_flags_resolver_proto_rawDescGZIP() []byte {
	file_mock_flags_resolver_proto_rawDescOnce.Do(func() {
		file_mock_flags_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mock_flags_resolver_proto_rawDesc), len(file_mock_flags_resolver_proto_rawDesc)))
	})
	return file_mock_flags_resolver_proto_rawDescData
}

var file_mock_flags_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mock_flags_resolver_proto_goTypes = []any{
	(*WriteFlagLogsRequest)(nil),  // 0: confidence.flags.resolver.v1.WriteFlagLogsRequest
	(*WriteFlagLogsResponse)(nil), // 1: confidence.flags.resolver.v1.WriteFlagLogsResponse
}
var file_mock_flags_resolver_proto_depIdxs = []int32{
	0, // 0: confidence.flags.resolver.v1.InternalFlagLoggerService.WriteFlagLogs:input_type -> confidence.flags.resolver.v1.WriteFlagLogsRequest
	1, // 1: confidence.flags.resolver.v1.InternalFlagLoggerService.WriteFlagLogs:output_type -> confidence.flags.resolver.v1.WriteFlagLogsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mock_flags_resolver_proto_init() }
func file_mock_flags_resolver_proto_init() {
	if File_mock_flags_resolver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_flags_resolver_proto_rawDesc), len(file_mock_flags_resolver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mock_flags_resolver_proto_goTypes,
		DependencyIndexes: file_mock_flags_resolver_proto_depIdxs,
		MessageInfos:      file_mock_flags_resolver_proto_msgTypes,
	}.Build()
	File_mock_flags_resolver_proto = out.File
	file_mock_flags_resolver_proto_goTypes = nil
	file_mock_flags_resolver_proto_depIdxs = nil
}
