// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: mock/flags_admin.proto

package mockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientResolverState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// using bytes here to simplify setting a state file.
	State []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The account the referenced state belongs to
	Account       string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResolverState) Reset() {
	*x = ClientResolverState{}
	mi := &file_mock_flags_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResolverState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResolverState) ProtoMessage() {}

func (x *ClientResolverState) ProtoReflect() protoreflect.Message {
	mi := &file_mock_flags_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResolverState.ProtoReflect.Descriptor instead.
func (*ClientResolverState) Descriptor() ([]byte, []int) {
	return file_mock_flags_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ClientResolverState) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ClientResolverState) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

var File_mock_flags_admin_proto protoreflect.FileDescriptor

const file_mock_flags_admin_proto_rawDesc = "" +
	"\n" +
	"\x16mock/flags_admin.proto\x12\x19confidence.flags.admin.v1\"E\n" +
	"\x13ClientResolverState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\fR\x05state\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccountBVZTgithub.com/spotify/confidence-resolver-rust/mock-support-server/genproto/mock;mockpbb\x06proto3"

var (
	file_mock_flags_admin_proto_rawDescOnce sync.Once
	file_mock_flags_admin_proto_rawDescData []byte
)

func file_mock_flags_admin_proto_rawDescGZIP() []byte {
	file_mock_flags_admin_proto_rawDescOnce.Do(func() {
		file_mock_flags_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mock_flags_admin_proto_rawDesc), len(file_mock_flags_admin_proto_rawDesc)))
	})
	return file_mock_flags_admin_proto_rawDescData
}

var file_mock_flags_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mock_flags_admin_proto_goTypes = []any{
	(*ClientResolverState)(nil), // 0: confidence.flags.admin.v1.ClientResolverState
}
var file_mock_flags_admin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mock_flags_admin_proto_init() }
func file_mock_flags_admin_proto_init() {
	if File_mock_flags_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_flags_admin_proto_rawDesc), len(file_mock_flags_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mock_flags_admin_proto_goTypes,
		DependencyIndexes: file_mock_flags_admin_proto_depIdxs,
		MessageInfos:      file_mock_flags_admin_proto_msgTypes,
	}.Build()
	File_mock_flags_admin_proto = out.File
	file_mock_flags_admin_proto_goTypes = nil
	file_mock_flags_admin_proto_depIdxs = nil
}
