// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: mock/iam.proto

package mockpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAccessTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The grant type. Currently only "client_credentials" is supported
	GrantType string `protobuf:"bytes,1,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	// The client id of the client to ge the token for
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The secret of the client to get the token for
	ClientSecret  string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccessTokenRequest) Reset() {
	*x = RequestAccessTokenRequest{}
	mi := &file_mock_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccessTokenRequest) ProtoMessage() {}

func (x *RequestAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mock_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*RequestAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_mock_iam_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAccessTokenRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *RequestAccessTokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RequestAccessTokenRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type AccessToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The access token that kan be used to call the api
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The ttl of the Access Token token from the time it was issued (in seconds).
	ExpiresIn     int64 `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_mock_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_mock_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_mock_iam_proto_rawDescGZIP(), []int{1}
}

func (x *AccessToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AccessToken) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_mock_iam_proto protoreflect.FileDescriptor

const file_mock_iam_proto_rawDesc = "" +
	"\n" +
	"\x0emock/iam.proto\x12\x11confidence.iam.v1\x1a\x1cgoogle/api/annotations.proto\"|\n" +
	"\x19RequestAccessTokenRequest\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x01 \x01(\tR\tgrantType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\"O\n" +
	"\vAccessToken\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn2\x8a\x01\n" +
	"\vAuthService\x12{\n" +
	"\x12RequestAccessToken\x12,.confidence.iam.v1.RequestAccessTokenRequest\x1a\x1e.confidence.iam.v1.AccessToken\"\x17\x82\xd3\xe4\x93\x02\x11\"\x0f/v1/oauth/tokenBVZTgithub.com/spotify/confidence-resolver-rust/mock-support-server/genproto/mock;mockpbb\x06proto3"

var (
	file_mock_iam_proto_rawDescOnce sync.Once
	file_mock_iam_proto_rawDescData []byte
)

func file_mock_iam_proto_rawDescGZIP() []byte {
	file_mock_iam_proto_rawDescOnce.Do(func() {
		file_mock_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mock_iam_proto_rawDesc), len(file_mock_iam_proto_rawDesc)))
	})
	return file_mock_iam_proto_rawDescData
}

var file_mock_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mock_iam_proto_goTypes = []any{
	(*RequestAccessTokenRequest)(nil), // 0: confidence.iam.v1.RequestAccessTokenRequest
	(*AccessToken)(nil),               // 1: confidence.iam.v1.AccessToken
}
var file_mock_iam_proto_depIdxs = []int32{
	0, // 0: confidence.iam.v1.AuthService.RequestAccessToken:input_type -> confidence.iam.v1.RequestAccessTokenRequest
	1, // 1: confidence.iam.v1.AuthService.RequestAccessToken:output_type -> confidence.iam.v1.AccessToken
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mock_iam_proto_init() }
func file_mock_iam_proto_init() {
	if File_mock_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_iam_proto_rawDesc), len(file_mock_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mock_iam_proto_goTypes,
		DependencyIndexes: file_mock_iam_proto_depIdxs,
		MessageInfos:      file_mock_iam_proto_msgTypes,
	}.Build()
	File_mock_iam_proto = out.File
	file_mock_iam_proto_goTypes = nil
	file_mock_iam_proto_depIdxs = nil
}
