// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: confidence/flags/resolver/v1/types.proto

package resolvertypes

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveReason int32

const (
	// Unspecified enum.
	ResolveReason_RESOLVE_REASON_UNSPECIFIED ResolveReason = 0
	// The flag was successfully resolved because one rule matched.
	ResolveReason_RESOLVE_REASON_MATCH ResolveReason = 1
	// The flag could not be resolved because no rule matched.
	ResolveReason_RESOLVE_REASON_NO_SEGMENT_MATCH ResolveReason = 2
	// The flag could not be resolved because the matching rule had no variant
	// that could be assigned.
	//
	// Deprecated: Marked as deprecated in confidence/flags/resolver/v1/types.proto.
	ResolveReason_RESOLVE_REASON_NO_TREATMENT_MATCH ResolveReason = 3
	// The flag could not be resolved because it was archived.
	ResolveReason_RESOLVE_REASON_FLAG_ARCHIVED ResolveReason = 4
	// The flag could not be resolved because the targeting key field was invalid
	ResolveReason_RESOLVE_REASON_TARGETING_KEY_ERROR ResolveReason = 5
	// Unknown error occurred during the resolve
	ResolveReason_RESOLVE_REASON_ERROR ResolveReason = 6
)

// Enum value maps for ResolveReason.
var (
	ResolveReason_name = map[int32]string{
		0: "RESOLVE_REASON_UNSPECIFIED",
		1: "RESOLVE_REASON_MATCH",
		2: "RESOLVE_REASON_NO_SEGMENT_MATCH",
		3: "RESOLVE_REASON_NO_TREATMENT_MATCH",
		4: "RESOLVE_REASON_FLAG_ARCHIVED",
		5: "RESOLVE_REASON_TARGETING_KEY_ERROR",
		6: "RESOLVE_REASON_ERROR",
	}
	ResolveReason_value = map[string]int32{
		"RESOLVE_REASON_UNSPECIFIED":         0,
		"RESOLVE_REASON_MATCH":               1,
		"RESOLVE_REASON_NO_SEGMENT_MATCH":    2,
		"RESOLVE_REASON_NO_TREATMENT_MATCH":  3,
		"RESOLVE_REASON_FLAG_ARCHIVED":       4,
		"RESOLVE_REASON_TARGETING_KEY_ERROR": 5,
		"RESOLVE_REASON_ERROR":               6,
	}
)

func (x ResolveReason) Enum() *ResolveReason {
	p := new(ResolveReason)
	*p = x
	return p
}

func (x ResolveReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolveReason) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_flags_resolver_v1_types_proto_enumTypes[0].Descriptor()
}

func (ResolveReason) Type() protoreflect.EnumType {
	return &file_confidence_flags_resolver_v1_types_proto_enumTypes[0]
}

func (x ResolveReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolveReason.Descriptor instead.
func (ResolveReason) EnumDescriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_types_proto_rawDescGZIP(), []int{0}
}

type SdkId int32

const (
	SdkId_SDK_ID_UNSPECIFIED                SdkId = 0
	SdkId_SDK_ID_JAVA_PROVIDER              SdkId = 1
	SdkId_SDK_ID_KOTLIN_PROVIDER            SdkId = 2
	SdkId_SDK_ID_SWIFT_PROVIDER             SdkId = 3
	SdkId_SDK_ID_JS_WEB_PROVIDER            SdkId = 4
	SdkId_SDK_ID_JS_SERVER_PROVIDER         SdkId = 5
	SdkId_SDK_ID_PYTHON_PROVIDER            SdkId = 6
	SdkId_SDK_ID_GO_PROVIDER                SdkId = 7
	SdkId_SDK_ID_RUBY_PROVIDER              SdkId = 8
	SdkId_SDK_ID_RUST_PROVIDER              SdkId = 9
	SdkId_SDK_ID_JAVA_CONFIDENCE            SdkId = 10
	SdkId_SDK_ID_KOTLIN_CONFIDENCE          SdkId = 11
	SdkId_SDK_ID_SWIFT_CONFIDENCE           SdkId = 12
	SdkId_SDK_ID_JS_CONFIDENCE              SdkId = 13
	SdkId_SDK_ID_PYTHON_CONFIDENCE          SdkId = 14
	SdkId_SDK_ID_GO_CONFIDENCE              SdkId = 15
	SdkId_SDK_ID_RUST_CONFIDENCE            SdkId = 16
	SdkId_SDK_ID_FLUTTER_IOS_CONFIDENCE     SdkId = 17
	SdkId_SDK_ID_FLUTTER_ANDROID_CONFIDENCE SdkId = 18
	SdkId_SDK_ID_DOTNET_CONFIDENCE          SdkId = 19
	SdkId_SDK_ID_GO_LOCAL_PROVIDER          SdkId = 20
	SdkId_SDK_ID_JAVA_LOCAL_PROVIDER        SdkId = 21
	SdkId_SDK_ID_JS_LOCAL_SERVER_PROVIDER   SdkId = 22
)

// Enum value maps for SdkId.
var (
	SdkId_name = map[int32]string{
		0:  "SDK_ID_UNSPECIFIED",
		1:  "SDK_ID_JAVA_PROVIDER",
		2:  "SDK_ID_KOTLIN_PROVIDER",
		3:  "SDK_ID_SWIFT_PROVIDER",
		4:  "SDK_ID_JS_WEB_PROVIDER",
		5:  "SDK_ID_JS_SERVER_PROVIDER",
		6:  "SDK_ID_PYTHON_PROVIDER",
		7:  "SDK_ID_GO_PROVIDER",
		8:  "SDK_ID_RUBY_PROVIDER",
		9:  "SDK_ID_RUST_PROVIDER",
		10: "SDK_ID_JAVA_CONFIDENCE",
		11: "SDK_ID_KOTLIN_CONFIDENCE",
		12: "SDK_ID_SWIFT_CONFIDENCE",
		13: "SDK_ID_JS_CONFIDENCE",
		14: "SDK_ID_PYTHON_CONFIDENCE",
		15: "SDK_ID_GO_CONFIDENCE",
		16: "SDK_ID_RUST_CONFIDENCE",
		17: "SDK_ID_FLUTTER_IOS_CONFIDENCE",
		18: "SDK_ID_FLUTTER_ANDROID_CONFIDENCE",
		19: "SDK_ID_DOTNET_CONFIDENCE",
		20: "SDK_ID_GO_LOCAL_PROVIDER",
		21: "SDK_ID_JAVA_LOCAL_PROVIDER",
		22: "SDK_ID_JS_LOCAL_SERVER_PROVIDER",
	}
	SdkId_value = map[string]int32{
		"SDK_ID_UNSPECIFIED":                0,
		"SDK_ID_JAVA_PROVIDER":              1,
		"SDK_ID_KOTLIN_PROVIDER":            2,
		"SDK_ID_SWIFT_PROVIDER":             3,
		"SDK_ID_JS_WEB_PROVIDER":            4,
		"SDK_ID_JS_SERVER_PROVIDER":         5,
		"SDK_ID_PYTHON_PROVIDER":            6,
		"SDK_ID_GO_PROVIDER":                7,
		"SDK_ID_RUBY_PROVIDER":              8,
		"SDK_ID_RUST_PROVIDER":              9,
		"SDK_ID_JAVA_CONFIDENCE":            10,
		"SDK_ID_KOTLIN_CONFIDENCE":          11,
		"SDK_ID_SWIFT_CONFIDENCE":           12,
		"SDK_ID_JS_CONFIDENCE":              13,
		"SDK_ID_PYTHON_CONFIDENCE":          14,
		"SDK_ID_GO_CONFIDENCE":              15,
		"SDK_ID_RUST_CONFIDENCE":            16,
		"SDK_ID_FLUTTER_IOS_CONFIDENCE":     17,
		"SDK_ID_FLUTTER_ANDROID_CONFIDENCE": 18,
		"SDK_ID_DOTNET_CONFIDENCE":          19,
		"SDK_ID_GO_LOCAL_PROVIDER":          20,
		"SDK_ID_JAVA_LOCAL_PROVIDER":        21,
		"SDK_ID_JS_LOCAL_SERVER_PROVIDER":   22,
	}
)

func (x SdkId) Enum() *SdkId {
	p := new(SdkId)
	*p = x
	return p
}

func (x SdkId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdkId) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_flags_resolver_v1_types_proto_enumTypes[1].Descriptor()
}

func (SdkId) Type() protoreflect.EnumType {
	return &file_confidence_flags_resolver_v1_types_proto_enumTypes[1]
}

func (x SdkId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdkId.Descriptor instead.
func (SdkId) EnumDescriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_types_proto_rawDescGZIP(), []int{1}
}

// (-- api-linter: core::0123::resource-annotation=disabled
//
//	aip.dev/not-precedent: SDKs are not internal Confidence resources. --)
type Sdk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the SDK used to interact with the API.
	//
	// Types that are valid to be assigned to Sdk:
	//
	//	*Sdk_Id
	//	*Sdk_CustomId
	Sdk isSdk_Sdk `protobuf_oneof:"sdk"`
	// Version of the SDK.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sdk) Reset() {
	*x = Sdk{}
	mi := &file_confidence_flags_resolver_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sdk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sdk) ProtoMessage() {}

func (x *Sdk) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sdk.ProtoReflect.Descriptor instead.
func (*Sdk) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Sdk) GetSdk() isSdk_Sdk {
	if x != nil {
		return x.Sdk
	}
	return nil
}

func (x *Sdk) GetId() SdkId {
	if x != nil {
		if x, ok := x.Sdk.(*Sdk_Id); ok {
			return x.Id
		}
	}
	return SdkId_SDK_ID_UNSPECIFIED
}

func (x *Sdk) GetCustomId() string {
	if x != nil {
		if x, ok := x.Sdk.(*Sdk_CustomId); ok {
			return x.CustomId
		}
	}
	return ""
}

func (x *Sdk) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type isSdk_Sdk interface {
	isSdk_Sdk()
}

type Sdk_Id struct {
	// Name of a Confidence SDKs.
	Id SdkId `protobuf:"varint,1,opt,name=id,proto3,enum=confidence.flags.resolver.v1.SdkId,oneof"`
}

type Sdk_CustomId struct {
	// Custom name for non-Confidence SDKs.
	CustomId string `protobuf:"bytes,2,opt,name=custom_id,json=customId,proto3,oneof"`
}

func (*Sdk_Id) isSdk_Sdk() {}

func (*Sdk_CustomId) isSdk_Sdk() {}

var File_confidence_flags_resolver_v1_types_proto protoreflect.FileDescriptor

const file_confidence_flags_resolver_v1_types_proto_rawDesc = "" +
	"\n" +
	"(confidence/flags/resolver/v1/types.proto\x12\x1cconfidence.flags.resolver.v1\x1a\x1fgoogle/api/field_behavior.proto\"\x82\x01\n" +
	"\x03Sdk\x125\n" +
	"\x02id\x18\x01 \x01(\x0e2#.confidence.flags.resolver.v1.SdkIdH\x00R\x02id\x12\x1d\n" +
	"\tcustom_id\x18\x02 \x01(\tH\x00R\bcustomId\x12\x1e\n" +
	"\aversion\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\aversionB\x05\n" +
	"\x03sdk*\xfd\x01\n" +
	"\rResolveReason\x12\x1e\n" +
	"\x1aRESOLVE_REASON_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RESOLVE_REASON_MATCH\x10\x01\x12#\n" +
	"\x1fRESOLVE_REASON_NO_SEGMENT_MATCH\x10\x02\x12)\n" +
	"!RESOLVE_REASON_NO_TREATMENT_MATCH\x10\x03\x1a\x02\b\x01\x12 \n" +
	"\x1cRESOLVE_REASON_FLAG_ARCHIVED\x10\x04\x12&\n" +
	"\"RESOLVE_REASON_TARGETING_KEY_ERROR\x10\x05\x12\x18\n" +
	"\x14RESOLVE_REASON_ERROR\x10\x06*\xa3\x05\n" +
	"\x05SdkId\x12\x16\n" +
	"\x12SDK_ID_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SDK_ID_JAVA_PROVIDER\x10\x01\x12\x1a\n" +
	"\x16SDK_ID_KOTLIN_PROVIDER\x10\x02\x12\x19\n" +
	"\x15SDK_ID_SWIFT_PROVIDER\x10\x03\x12\x1a\n" +
	"\x16SDK_ID_JS_WEB_PROVIDER\x10\x04\x12\x1d\n" +
	"\x19SDK_ID_JS_SERVER_PROVIDER\x10\x05\x12\x1a\n" +
	"\x16SDK_ID_PYTHON_PROVIDER\x10\x06\x12\x16\n" +
	"\x12SDK_ID_GO_PROVIDER\x10\a\x12\x18\n" +
	"\x14SDK_ID_RUBY_PROVIDER\x10\b\x12\x18\n" +
	"\x14SDK_ID_RUST_PROVIDER\x10\t\x12\x1a\n" +
	"\x16SDK_ID_JAVA_CONFIDENCE\x10\n" +
	"\x12\x1c\n" +
	"\x18SDK_ID_KOTLIN_CONFIDENCE\x10\v\x12\x1b\n" +
	"\x17SDK_ID_SWIFT_CONFIDENCE\x10\f\x12\x18\n" +
	"\x14SDK_ID_JS_CONFIDENCE\x10\r\x12\x1c\n" +
	"\x18SDK_ID_PYTHON_CONFIDENCE\x10\x0e\x12\x18\n" +
	"\x14SDK_ID_GO_CONFIDENCE\x10\x0f\x12\x1a\n" +
	"\x16SDK_ID_RUST_CONFIDENCE\x10\x10\x12!\n" +
	"\x1dSDK_ID_FLUTTER_IOS_CONFIDENCE\x10\x11\x12%\n" +
	"!SDK_ID_FLUTTER_ANDROID_CONFIDENCE\x10\x12\x12\x1c\n" +
	"\x18SDK_ID_DOTNET_CONFIDENCE\x10\x13\x12\x1c\n" +
	"\x18SDK_ID_GO_LOCAL_PROVIDER\x10\x14\x12\x1e\n" +
	"\x1aSDK_ID_JAVA_LOCAL_PROVIDER\x10\x15\x12#\n" +
	"\x1fSDK_ID_JS_LOCAL_SERVER_PROVIDER\x10\x16B8\n" +
	"(com.spotify.confidence.flags.resolver.v1B\n" +
	"TypesProtoP\x01b\x06proto3"

var (
	file_confidence_flags_resolver_v1_types_proto_rawDescOnce sync.Once
	file_confidence_flags_resolver_v1_types_proto_rawDescData []byte
)

func file_confidence_flags_resolver_v1_types_proto_rawDescGZIP() []byte {
	file_confidence_flags_resolver_v1_types_proto_rawDescOnce.Do(func() {
		file_confidence_flags_resolver_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_flags_resolver_v1_types_proto_rawDesc), len(file_confidence_flags_resolver_v1_types_proto_rawDesc)))
	})
	return file_confidence_flags_resolver_v1_types_proto_rawDescData
}

var file_confidence_flags_resolver_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_confidence_flags_resolver_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_confidence_flags_resolver_v1_types_proto_goTypes = []any{
	(ResolveReason)(0), // 0: confidence.flags.resolver.v1.ResolveReason
	(SdkId)(0),         // 1: confidence.flags.resolver.v1.SdkId
	(*Sdk)(nil),        // 2: confidence.flags.resolver.v1.Sdk
}
var file_confidence_flags_resolver_v1_types_proto_depIdxs = []int32{
	1, // 0: confidence.flags.resolver.v1.Sdk.id:type_name -> confidence.flags.resolver.v1.SdkId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_confidence_flags_resolver_v1_types_proto_init() }
func file_confidence_flags_resolver_v1_types_proto_init() {
	if File_confidence_flags_resolver_v1_types_proto != nil {
		return
	}
	file_confidence_flags_resolver_v1_types_proto_msgTypes[0].OneofWrappers = []any{
		(*Sdk_Id)(nil),
		(*Sdk_CustomId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_flags_resolver_v1_types_proto_rawDesc), len(file_confidence_flags_resolver_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_confidence_flags_resolver_v1_types_proto_goTypes,
		DependencyIndexes: file_confidence_flags_resolver_v1_types_proto_depIdxs,
		EnumInfos:         file_confidence_flags_resolver_v1_types_proto_enumTypes,
		MessageInfos:      file_confidence_flags_resolver_v1_types_proto_msgTypes,
	}.Build()
	File_confidence_flags_resolver_v1_types_proto = out.File
	file_confidence_flags_resolver_v1_types_proto_goTypes = nil
	file_confidence_flags_resolver_v1_types_proto_depIdxs = nil
}
