name: CloudFlare Deployer Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'wasm/**'
      - 'wasm-msg/**'
      - 'data/**'
  pull_request:
    paths-ignore:
      - 'wasm/**'
      - 'wasm-msg/**'
      - 'data/**'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: build-image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/confidence-cloudflare-deployer
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./confidence-cloudflare-resolver/deployer/Dockerfile
          push: false
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


