name: Docker Build (Reusable)

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      targets:
        required: true
        type: string
        description: 'Comma-separated list of Docker targets to build'
      upload-artifact:
        required: false
        type: boolean
        default: false
        description: 'Whether to extract and upload WASM artifact'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: ${{ inputs.job-name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build targets
        run: |
          IFS=',' read -ra TARGETS <<< "${{ inputs.targets }}"
          for target in "${TARGETS[@]}"; do
            echo "Building target: $target"
            docker buildx build \
              --target=$target \
              --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}/cache:main \
              ${{ github.event_name == 'push' && format('--cache-to=type=registry,ref=ghcr.io/{0}/cache:main,mode=max', github.repository) || '' }} \
              .
          done

      - name: Extract WASM artifact
        if: inputs.upload-artifact
        run: |
          mkdir -p artifacts
          docker build --target=wasm-rust-guest.artifact --output=type=local,dest=./artifacts .

      - name: Upload WASM artifact
        if: inputs.upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-module
          path: artifacts/confidence_resolver.wasm

